### PR TITLE
Revert "Fix images_with_captions code snippet in README"

### PR DESCRIPTION
**Pull request by parndt**
Reverts refinery/refinerycms-page-images#123

@anitagraham wasn't happy

### CODE REVIEW

**Comment by parndt** [comment]
>I deliberately used `<figure>` and `<figcaption>` in the third example as they are the appropriate 
HTML5 elements. There are already two examples on the page using 
`<ul>/<li>/<span class=‘caption’>`.

> If you must have three sets of close to identical tags, then use HTML5.

> - @anitagraham

**Comment by bricesanchez** [comment]
Ok, so the problem is the usage of ul li instead of figure tags not the ruby code ?
So i should update the README to re-add HTML5 tags ?!

**Comment by parndt** [comment]
Just use my revert branch and commit only Ruby changes, or we can figure out why you can't use dot notation.. up to you?

**Comment by bricesanchez** [comment]
Done @parndt !
Thanks for your feedback @anitagraham, i want you happy :)

**Comment by parndt** [comment]
@anitagraham what do you think?

**Comment by anitagraham** [comment]
happy. :smiley:

**Pull request merged**
